---
title: "`demethr` full pipeline"
author: "Florence Pittion, Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true    
  pdf_document:
    keep_tex: true
---



```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide", warning=FALSE)
```

# Objectiv


```{r}
if (!exists("tcga_project"))         { tcga_project = "TCGA-LUSC"   ;}
if (!exists("nb_rnd_feat"))          { nb_rnd_feat = 0              ;}
if (!exists("ud_str"))               { ud_str = 2500                ;}
if (!exists("feature_pretreatments")){ feature_pretreatment = "raw" ;}
if (!exists("reducer_func2_names"))  { reducer_func2_name = "mean" ;}
prefix3 = paste0(feature_pretreatment, "_", ud_str, "_", nb_rnd_feat, "_", reducer_func2_name)  
```

```{r child="01_tss_cpg_status.Rmd"}
```

```{r child="02_mapreduce_mean.Rmd"}
```

# Step 3: Activation in demethylating context


```{r child="03_da_GSE45332.Rmd"}
```

```{r child="03_da_GSE5816.Rmd"}
```

```{r child="03_da_summary.Rmd"}
```

```{r child="04_results.Rmd"}
```



# Session Information

```{r, results="verbatim"}
sessionInfo()
```



